alias a='git add '
alias aa='git add --all '
alias b='git branch '
alias c='git commit --message '
alias ca='git add --all && git commit --message '
alias co='git checkout '
alias d='git diff '
alias l='git log --graph --abbrev-commit --decorate --date=relative --format=format:"%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(dim white)- %an%C(reset)%C(bold yellow)%d%C(reset)"'
alias m='git merge '
alias r='git rm '
alias reword='git commit --amend -m'
alias s='git status'